import ClassRaceData from "./ClassRaceData";

export default class ClassachievementData {
    private m_represent: ClassRaceData
    private m_achievements: {[ID:number]: ClassRaceData | null}
    constructor(represent: ClassRaceData) {
        this.m_represent = represent
        this.m_achievements = {}
        this.constructorachievements()
    }

    public updateAchievement(data: ClassRaceData) {
        this.m_achievements[data.ID] = data
    }
    public getIDAchievementData(ID: number) {
        if (this.m_achievements[ID] != undefined) {
            return this.m_achievements[ID]
        } else {
            return null
        }
    }
    public get represent() { return this.m_represent}
    public get achievements() { return this.m_achievements}

    private constructorachievements(){
        this.m_achievements[ClassachievementData.ID1] = null
        this.m_achievements[ClassachievementData.ID2] = null
        this.m_achievements[ClassachievementData.ID3] = null
        this.m_achievements[ClassachievementData.ID4] = null
        this.m_achievements[ClassachievementData.ID5] = null
        this.m_achievements[ClassachievementData.ID6] = null
        this.m_achievements[ClassachievementData.ID7] = null
        this.m_achievements[ClassachievementData.ID8] = null
        this.m_achievements[ClassachievementData.ID9] = null
        this.m_achievements[ClassachievementData.ID10] = null
        this.m_achievements[ClassachievementData.ID11] = null
        this.m_achievements[ClassachievementData.ID12] = null
        this.m_achievements[ClassachievementData.ID13] = null
        this.m_achievements[ClassachievementData.ID14] = null
        this.m_achievements[ClassachievementData.ID15] = null
        this.m_achievements[ClassachievementData.ID16] = null
        this.m_achievements[ClassachievementData.ID17] = null
        this.m_achievements[ClassachievementData.ID18] = null
        this.m_achievements[ClassachievementData.ID19] = null
        this.m_achievements[ClassachievementData.ID20] = null
        this.m_achievements[ClassachievementData.ID21] = null
        this.m_achievements[ClassachievementData.ID22] = null
        this.m_achievements[ClassachievementData.ID23] = null
        this.m_achievements[ClassachievementData.ID24] = null
        this.m_achievements[ClassachievementData.ID25] = null
        this.m_achievements[ClassachievementData.ID26] = null
        this.m_achievements[ClassachievementData.ID27] = null
        this.m_achievements[ClassachievementData.ID28] = null
        this.m_achievements[ClassachievementData.ID29] = null
        this.m_achievements[ClassachievementData.ID30] = null
        this.m_achievements[ClassachievementData.ID31] = null
        this.m_achievements[ClassachievementData.ID32] = null
        this.m_achievements[ClassachievementData.ID33] = null
        this.m_achievements[ClassachievementData.ID34] = null
        this.m_achievements[ClassachievementData.ID35] = null
        this.m_achievements[ClassachievementData.ID36] = null
        this.m_achievements[ClassachievementData.ID37] = null
        this.m_achievements[ClassachievementData.ID38] = null
        this.m_achievements[ClassachievementData.ID39] = null
        this.m_achievements[ClassachievementData.ID40] = null
        this.m_achievements[ClassachievementData.ID41] = null
        this.m_achievements[ClassachievementData.ID42] = null
        this.m_achievements[ClassachievementData.ID43] = null
        this.m_achievements[ClassachievementData.ID44] = null
        this.m_achievements[ClassachievementData.ID45] = null
        this.m_achievements[ClassachievementData.ID46] = null
        this.m_achievements[ClassachievementData.ID47] = null
        this.m_achievements[ClassachievementData.ID48] = null
        this.m_achievements[ClassachievementData.ID49] = null
        this.m_achievements[ClassachievementData.ID50] = null
        this.m_achievements[ClassachievementData.ID51] = null
        this.m_achievements[ClassachievementData.ID52] = null
        this.m_achievements[ClassachievementData.ID53] = null
        this.m_achievements[ClassachievementData.ID54] = null
        this.m_achievements[ClassachievementData.ID55] = null
        this.m_achievements[ClassachievementData.ID56] = null
        this.m_achievements[ClassachievementData.ID57] = null
        this.m_achievements[ClassachievementData.ID58] = null
        this.m_achievements[ClassachievementData.ID59] = null
        this.m_achievements[ClassachievementData.ID60] = null
        this.m_achievements[ClassachievementData.ID61] = null
        this.m_achievements[ClassachievementData.ID62] = null
        this.m_achievements[ClassachievementData.ID63] = null
        this.m_achievements[ClassachievementData.ID64] = null
        this.m_achievements[ClassachievementData.ID65] = null
        this.m_achievements[ClassachievementData.ID66] = null
        this.m_achievements[ClassachievementData.ID67] = null
        this.m_achievements[ClassachievementData.ID68] = null
        this.m_achievements[ClassachievementData.ID69] = null
        this.m_achievements[ClassachievementData.ID70] = null
        this.m_achievements[ClassachievementData.ID71] = null
        this.m_achievements[ClassachievementData.ID72] = null
        this.m_achievements[ClassachievementData.ID73] = null
        this.m_achievements[ClassachievementData.ID74] = null
        this.m_achievements[ClassachievementData.ID75] = null
        this.m_achievements[ClassachievementData.ID76] = null
        this.m_achievements[ClassachievementData.ID77] = null
        this.m_achievements[ClassachievementData.ID78] = null
        this.m_achievements[ClassachievementData.ID79] = null
        this.m_achievements[ClassachievementData.ID80] = null
        this.m_achievements[ClassachievementData.ID81] = null
        this.m_achievements[ClassachievementData.ID82] = null
        this.m_achievements[ClassachievementData.ID83] = null
        this.m_achievements[ClassachievementData.ID84] = null
        this.m_achievements[ClassachievementData.ID85] = null
        this.m_achievements[ClassachievementData.ID86] = null
        this.m_achievements[ClassachievementData.ID87] = null
        this.m_achievements[ClassachievementData.ID88] = null
        this.m_achievements[ClassachievementData.ID89] = null
        this.m_achievements[ClassachievementData.ID90] = null
        this.m_achievements[ClassachievementData.ID91] = null
        this.m_achievements[ClassachievementData.ID92] = null
        this.m_achievements[ClassachievementData.ID93] = null
        this.m_achievements[ClassachievementData.ID94] = null
        this.m_achievements[ClassachievementData.ID95] = null
        this.m_achievements[ClassachievementData.ID96] = null
        this.m_achievements[ClassachievementData.ID97] = null
        this.m_achievements[ClassachievementData.ID98] = null
        this.m_achievements[ClassachievementData.ID99] = null
        this.m_achievements[ClassachievementData.ID100] = null
        this.m_achievements[ClassachievementData.ID101] = null
        this.m_achievements[ClassachievementData.ID102] = null
        this.m_achievements[ClassachievementData.ID103] = null
        this.m_achievements[ClassachievementData.ID104] = null
        this.m_achievements[ClassachievementData.ID105] = null
        this.m_achievements[ClassachievementData.ID106] = null
        this.m_achievements[ClassachievementData.ID107] = null
        this.m_achievements[ClassachievementData.ID108] = null
        this.m_achievements[ClassachievementData.ID109] = null
        this.m_achievements[ClassachievementData.ID110] = null
        this.m_achievements[ClassachievementData.ID111] = null
        this.m_achievements[ClassachievementData.ID112] = null
        this.m_achievements[ClassachievementData.ID113] = null
        this.m_achievements[ClassachievementData.ID114] = null
        this.m_achievements[ClassachievementData.ID115] = null
        this.m_achievements[ClassachievementData.ID116] = null
        this.m_achievements[ClassachievementData.ID117] = null
        this.m_achievements[ClassachievementData.ID118] = null
        this.m_achievements[ClassachievementData.ID119] = null
        this.m_achievements[ClassachievementData.ID120] = null
        this.m_achievements[ClassachievementData.ID121] = null
        this.m_achievements[ClassachievementData.ID122] = null
        this.m_achievements[ClassachievementData.ID123] = null
        this.m_achievements[ClassachievementData.ID124] = null
        this.m_achievements[ClassachievementData.ID125] = null
        this.m_achievements[ClassachievementData.ID126] = null
        this.m_achievements[ClassachievementData.ID127] = null
        this.m_achievements[ClassachievementData.ID128] = null
        this.m_achievements[ClassachievementData.ID129] = null
        this.m_achievements[ClassachievementData.ID130] = null
        this.m_achievements[ClassachievementData.ID131] = null
        this.m_achievements[ClassachievementData.ID132] = null
        this.m_achievements[ClassachievementData.ID133] = null
        this.m_achievements[ClassachievementData.ID134] = null
        this.m_achievements[ClassachievementData.ID135] = null
        this.m_achievements[ClassachievementData.ID136] = null
        this.m_achievements[ClassachievementData.ID137] = null
        this.m_achievements[ClassachievementData.ID138] = null
        this.m_achievements[ClassachievementData.ID139] = null
        this.m_achievements[ClassachievementData.ID140] = null
        this.m_achievements[ClassachievementData.ID141] = null
        this.m_achievements[ClassachievementData.ID142] = null
        this.m_achievements[ClassachievementData.ID143] = null
        this.m_achievements[ClassachievementData.ID144] = null
        this.m_achievements[ClassachievementData.ID145] = null
        this.m_achievements[ClassachievementData.ID146] = null
        this.m_achievements[ClassachievementData.ID147] = null
        this.m_achievements[ClassachievementData.ID148] = null
        this.m_achievements[ClassachievementData.ID149] = null
        this.m_achievements[ClassachievementData.ID150] = null
        this.m_achievements[ClassachievementData.ID151] = null
        this.m_achievements[ClassachievementData.ID152] = null
        this.m_achievements[ClassachievementData.ID153] = null
        this.m_achievements[ClassachievementData.ID154] = null
        this.m_achievements[ClassachievementData.ID155] = null
        this.m_achievements[ClassachievementData.ID156] = null
        this.m_achievements[ClassachievementData.ID157] = null
        this.m_achievements[ClassachievementData.ID158] = null
        this.m_achievements[ClassachievementData.ID159] = null
        this.m_achievements[ClassachievementData.ID160] = null
        this.m_achievements[ClassachievementData.ID161] = null
        this.m_achievements[ClassachievementData.ID162] = null
        this.m_achievements[ClassachievementData.ID163] = null
        this.m_achievements[ClassachievementData.ID164] = null
        this.m_achievements[ClassachievementData.ID165] = null
        this.m_achievements[ClassachievementData.ID166] = null
        this.m_achievements[ClassachievementData.ID167] = null
        this.m_achievements[ClassachievementData.ID168] = null
        this.m_achievements[ClassachievementData.ID169] = null
        this.m_achievements[ClassachievementData.ID170] = null
        this.m_achievements[ClassachievementData.ID171] = null
        this.m_achievements[ClassachievementData.ID172] = null
        this.m_achievements[ClassachievementData.ID173] = null
        this.m_achievements[ClassachievementData.ID174] = null
        this.m_achievements[ClassachievementData.ID175] = null
        this.m_achievements[ClassachievementData.ID176] = null
        this.m_achievements[ClassachievementData.ID177] = null
        this.m_achievements[ClassachievementData.ID178] = null
        this.m_achievements[ClassachievementData.ID179] = null
        this.m_achievements[ClassachievementData.ID180] = null
        this.m_achievements[ClassachievementData.ID181] = null
        this.m_achievements[ClassachievementData.ID182] = null
        this.m_achievements[ClassachievementData.ID183] = null
        this.m_achievements[ClassachievementData.ID184] = null
        this.m_achievements[ClassachievementData.ID185] = null
        this.m_achievements[ClassachievementData.ID186] = null
        this.m_achievements[ClassachievementData.ID187] = null
        this.m_achievements[ClassachievementData.ID188] = null
        this.m_achievements[ClassachievementData.ID189] = null
        this.m_achievements[ClassachievementData.ID190] = null
        this.m_achievements[ClassachievementData.ID191] = null
        this.m_achievements[ClassachievementData.ID192] = null
        this.m_achievements[ClassachievementData.ID193] = null
        this.m_achievements[ClassachievementData.ID194] = null
        this.m_achievements[ClassachievementData.ID195] = null
        this.m_achievements[ClassachievementData.ID196] = null
        this.m_achievements[ClassachievementData.ID197] = null
        this.m_achievements[ClassachievementData.ID198] = null
        this.m_achievements[ClassachievementData.ID199] = null
        this.m_achievements[ClassachievementData.ID200] = null
        this.m_achievements[ClassachievementData.ID201] = null
        this.m_achievements[ClassachievementData.ID202] = null
        this.m_achievements[ClassachievementData.ID203] = null
        this.m_achievements[ClassachievementData.ID204] = null
        this.m_achievements[ClassachievementData.ID205] = null
        this.m_achievements[ClassachievementData.ID206] = null
        this.m_achievements[ClassachievementData.ID207] = null
        this.m_achievements[ClassachievementData.ID208] = null
        this.m_achievements[ClassachievementData.ID209] = null
        this.m_achievements[ClassachievementData.ID210] = null
        this.m_achievements[ClassachievementData.ID211] = null
        this.m_achievements[ClassachievementData.ID212] = null
        this.m_achievements[ClassachievementData.ID213] = null
        this.m_achievements[ClassachievementData.ID214] = null
        this.m_achievements[ClassachievementData.ID215] = null
        this.m_achievements[ClassachievementData.ID216] = null
        this.m_achievements[ClassachievementData.ID217] = null
        this.m_achievements[ClassachievementData.ID218] = null
        this.m_achievements[ClassachievementData.ID219] = null
        this.m_achievements[ClassachievementData.ID220] = null
        this.m_achievements[ClassachievementData.ID221] = null
        this.m_achievements[ClassachievementData.ID222] = null
        this.m_achievements[ClassachievementData.ID223] = null
        this.m_achievements[ClassachievementData.ID224] = null
        this.m_achievements[ClassachievementData.ID225] = null
        this.m_achievements[ClassachievementData.ID226] = null
        this.m_achievements[ClassachievementData.ID227] = null
        this.m_achievements[ClassachievementData.ID228] = null
        this.m_achievements[ClassachievementData.ID229] = null
        this.m_achievements[ClassachievementData.ID230] = null
        this.m_achievements[ClassachievementData.ID231] = null
        this.m_achievements[ClassachievementData.ID232] = null
        this.m_achievements[ClassachievementData.ID233] = null
        this.m_achievements[ClassachievementData.ID234] = null
        this.m_achievements[ClassachievementData.ID235] = null
        this.m_achievements[ClassachievementData.ID236] = null
        this.m_achievements[ClassachievementData.ID237] = null
        this.m_achievements[ClassachievementData.ID238] = null
        this.m_achievements[ClassachievementData.ID239] = null
        this.m_achievements[ClassachievementData.ID240] = null
        this.m_achievements[ClassachievementData.ID241] = null
        this.m_achievements[ClassachievementData.ID242] = null
        this.m_achievements[ClassachievementData.ID243] = null
        this.m_achievements[ClassachievementData.ID244] = null
        this.m_achievements[ClassachievementData.ID245] = null
        this.m_achievements[ClassachievementData.ID246] = null
        this.m_achievements[ClassachievementData.ID247] = null
        this.m_achievements[ClassachievementData.ID248] = null
        this.m_achievements[ClassachievementData.ID249] = null
        this.m_achievements[ClassachievementData.ID250] = null
        this.m_achievements[ClassachievementData.ID251] = null
        this.m_achievements[ClassachievementData.ID252] = null
        this.m_achievements[ClassachievementData.ID253] = null
        this.m_achievements[ClassachievementData.ID254] = null
        this.m_achievements[ClassachievementData.ID255] = null
        this.m_achievements[ClassachievementData.ID256] = null
        this.m_achievements[ClassachievementData.ID257] = null
        this.m_achievements[ClassachievementData.ID258] = null
        this.m_achievements[ClassachievementData.ID259] = null
        this.m_achievements[ClassachievementData.ID260] = null
        this.m_achievements[ClassachievementData.ID261] = null
        this.m_achievements[ClassachievementData.ID262] = null
        this.m_achievements[ClassachievementData.ID263] = null
        this.m_achievements[ClassachievementData.ID264] = null
        this.m_achievements[ClassachievementData.ID265] = null
        this.m_achievements[ClassachievementData.ID266] = null
        this.m_achievements[ClassachievementData.ID267] = null
        this.m_achievements[ClassachievementData.ID268] = null
        this.m_achievements[ClassachievementData.ID269] = null
        this.m_achievements[ClassachievementData.ID270] = null
        this.m_achievements[ClassachievementData.ID271] = null
        this.m_achievements[ClassachievementData.ID272] = null
        this.m_achievements[ClassachievementData.ID273] = null
        this.m_achievements[ClassachievementData.ID274] = null
        this.m_achievements[ClassachievementData.ID275] = null
        this.m_achievements[ClassachievementData.ID276] = null
        this.m_achievements[ClassachievementData.ID277] = null
        this.m_achievements[ClassachievementData.ID278] = null
        this.m_achievements[ClassachievementData.ID279] = null
        this.m_achievements[ClassachievementData.ID280] = null
        this.m_achievements[ClassachievementData.ID281] = null
        this.m_achievements[ClassachievementData.ID282] = null
        this.m_achievements[ClassachievementData.ID283] = null
        this.m_achievements[ClassachievementData.ID284] = null
        this.m_achievements[ClassachievementData.ID285] = null
        this.m_achievements[ClassachievementData.ID286] = null
        this.m_achievements[ClassachievementData.ID287] = null
        this.m_achievements[ClassachievementData.ID288] = null
        this.m_achievements[ClassachievementData.ID289] = null
        this.m_achievements[ClassachievementData.ID290] = null
        this.m_achievements[ClassachievementData.ID291] = null
        this.m_achievements[ClassachievementData.ID292] = null
        this.m_achievements[ClassachievementData.ID293] = null
        this.m_achievements[ClassachievementData.ID294] = null
        this.m_achievements[ClassachievementData.ID295] = null
        this.m_achievements[ClassachievementData.ID296] = null
        this.m_achievements[ClassachievementData.ID297] = null
        this.m_achievements[ClassachievementData.ID298] = null
        this.m_achievements[ClassachievementData.ID299] = null
        this.m_achievements[ClassachievementData.ID300] = null
        this.m_achievements[ClassachievementData.ID301] = null
        this.m_achievements[ClassachievementData.ID302] = null
        this.m_achievements[ClassachievementData.ID303] = null
        this.m_achievements[ClassachievementData.ID304] = null
        this.m_achievements[ClassachievementData.ID305] = null
        this.m_achievements[ClassachievementData.ID306] = null
        this.m_achievements[ClassachievementData.ID307] = null
        this.m_achievements[ClassachievementData.ID308] = null
        this.m_achievements[ClassachievementData.ID309] = null
        this.m_achievements[ClassachievementData.ID310] = null
        this.m_achievements[ClassachievementData.ID311] = null
        this.m_achievements[ClassachievementData.ID312] = null
        this.m_achievements[ClassachievementData.ID313] = null
        this.m_achievements[ClassachievementData.ID314] = null
        this.m_achievements[ClassachievementData.ID315] = null
        this.m_achievements[ClassachievementData.ID316] = null
        this.m_achievements[ClassachievementData.ID317] = null
        this.m_achievements[ClassachievementData.ID318] = null
        this.m_achievements[ClassachievementData.ID319] = null
        this.m_achievements[ClassachievementData.ID320] = null
        this.m_achievements[ClassachievementData.ID321] = null
        this.m_achievements[ClassachievementData.ID322] = null
        this.m_achievements[ClassachievementData.ID323] = null
        this.m_achievements[ClassachievementData.ID324] = null
        this.m_achievements[ClassachievementData.ID325] = null
        this.m_achievements[ClassachievementData.ID326] = null
        this.m_achievements[ClassachievementData.ID327] = null
        this.m_achievements[ClassachievementData.ID328] = null
        this.m_achievements[ClassachievementData.ID329] = null
        this.m_achievements[ClassachievementData.ID330] = null
        this.m_achievements[ClassachievementData.ID331] = null
        this.m_achievements[ClassachievementData.ID332] = null
        this.m_achievements[ClassachievementData.ID333] = null
        this.m_achievements[ClassachievementData.ID334] = null
        this.m_achievements[ClassachievementData.ID335] = null
        this.m_achievements[ClassachievementData.ID336] = null
        this.m_achievements[ClassachievementData.ID337] = null
        this.m_achievements[ClassachievementData.ID338] = null
        this.m_achievements[ClassachievementData.ID339] = null
        this.m_achievements[ClassachievementData.ID340] = null
        this.m_achievements[ClassachievementData.ID341] = null
        this.m_achievements[ClassachievementData.ID342] = null
        this.m_achievements[ClassachievementData.ID343] = null
        this.m_achievements[ClassachievementData.ID344] = null
        this.m_achievements[ClassachievementData.ID345] = null
        this.m_achievements[ClassachievementData.ID346] = null
        this.m_achievements[ClassachievementData.ID347] = null
        this.m_achievements[ClassachievementData.ID348] = null
        this.m_achievements[ClassachievementData.ID349] = null
        this.m_achievements[ClassachievementData.ID350] = null
        this.m_achievements[ClassachievementData.ID351] = null
        this.m_achievements[ClassachievementData.ID352] = null
        this.m_achievements[ClassachievementData.ID353] = null
        this.m_achievements[ClassachievementData.ID354] = null
        this.m_achievements[ClassachievementData.ID355] = null
        this.m_achievements[ClassachievementData.ID356] = null
        this.m_achievements[ClassachievementData.ID357] = null
        this.m_achievements[ClassachievementData.ID358] = null
        this.m_achievements[ClassachievementData.ID359] = null
        this.m_achievements[ClassachievementData.ID360] = null
        this.m_achievements[ClassachievementData.ID361] = null
        this.m_achievements[ClassachievementData.ID362] = null
        this.m_achievements[ClassachievementData.ID363] = null
        this.m_achievements[ClassachievementData.ID364] = null
        this.m_achievements[ClassachievementData.ID365] = null
        this.m_achievements[ClassachievementData.ID366] = null
        this.m_achievements[ClassachievementData.ID367] = null
        this.m_achievements[ClassachievementData.ID368] = null
        this.m_achievements[ClassachievementData.ID369] = null
        this.m_achievements[ClassachievementData.ID370] = null
        this.m_achievements[ClassachievementData.ID371] = null
        this.m_achievements[ClassachievementData.ID372] = null
        this.m_achievements[ClassachievementData.ID373] = null
        this.m_achievements[ClassachievementData.ID374] = null
        this.m_achievements[ClassachievementData.ID375] = null
        this.m_achievements[ClassachievementData.ID376] = null
        this.m_achievements[ClassachievementData.ID377] = null
        this.m_achievements[ClassachievementData.ID378] = null
        this.m_achievements[ClassachievementData.ID379] = null
        this.m_achievements[ClassachievementData.ID380] = null
        this.m_achievements[ClassachievementData.ID381] = null
        this.m_achievements[ClassachievementData.ID382] = null
        this.m_achievements[ClassachievementData.ID383] = null
        this.m_achievements[ClassachievementData.ID384] = null
        this.m_achievements[ClassachievementData.ID385] = null
        this.m_achievements[ClassachievementData.ID386] = null
        this.m_achievements[ClassachievementData.ID387] = null
        this.m_achievements[ClassachievementData.ID388] = null
        this.m_achievements[ClassachievementData.ID389] = null
        this.m_achievements[ClassachievementData.ID390] = null
        this.m_achievements[ClassachievementData.ID391] = null
        this.m_achievements[ClassachievementData.ID392] = null
        this.m_achievements[ClassachievementData.ID393] = null
        this.m_achievements[ClassachievementData.ID394] = null
        this.m_achievements[ClassachievementData.ID395] = null
        this.m_achievements[ClassachievementData.ID396] = null
        this.m_achievements[ClassachievementData.ID397] = null
        this.m_achievements[ClassachievementData.ID398] = null
        this.m_achievements[ClassachievementData.ID399] = null
        this.m_achievements[ClassachievementData.ID400] = null
        this.m_achievements[ClassachievementData.ID401] = null
        this.m_achievements[ClassachievementData.ID402] = null
        this.m_achievements[ClassachievementData.ID403] = null
        this.m_achievements[ClassachievementData.ID404] = null
        this.m_achievements[ClassachievementData.ID405] = null
        this.m_achievements[ClassachievementData.ID406] = null
        this.m_achievements[ClassachievementData.ID407] = null
        this.m_achievements[ClassachievementData.ID408] = null
        this.m_achievements[ClassachievementData.ID409] = null
        this.m_achievements[ClassachievementData.ID410] = null
        this.m_achievements[ClassachievementData.ID411] = null
        this.m_achievements[ClassachievementData.ID412] = null
        this.m_achievements[ClassachievementData.ID413] = null
        this.m_achievements[ClassachievementData.ID414] = null
        this.m_achievements[ClassachievementData.ID415] = null
        this.m_achievements[ClassachievementData.ID416] = null
        this.m_achievements[ClassachievementData.ID417] = null
        this.m_achievements[ClassachievementData.ID418] = null
        this.m_achievements[ClassachievementData.ID419] = null
        this.m_achievements[ClassachievementData.ID420] = null
        this.m_achievements[ClassachievementData.ID421] = null
        this.m_achievements[ClassachievementData.ID422] = null
        this.m_achievements[ClassachievementData.ID423] = null
        this.m_achievements[ClassachievementData.ID424] = null
        this.m_achievements[ClassachievementData.ID425] = null
        this.m_achievements[ClassachievementData.ID426] = null
        this.m_achievements[ClassachievementData.ID427] = null
        this.m_achievements[ClassachievementData.ID428] = null
        this.m_achievements[ClassachievementData.ID429] = null
        this.m_achievements[ClassachievementData.ID430] = null
        this.m_achievements[ClassachievementData.ID431] = null
        this.m_achievements[ClassachievementData.ID432] = null
        this.m_achievements[ClassachievementData.ID433] = null
        this.m_achievements[ClassachievementData.ID434] = null
        this.m_achievements[ClassachievementData.ID435] = null
        this.m_achievements[ClassachievementData.ID436] = null
        this.m_achievements[ClassachievementData.ID437] = null
        this.m_achievements[ClassachievementData.ID438] = null
        this.m_achievements[ClassachievementData.ID439] = null
        this.m_achievements[ClassachievementData.ID440] = null
        this.m_achievements[ClassachievementData.ID441] = null
        this.m_achievements[ClassachievementData.ID442] = null
        this.m_achievements[ClassachievementData.ID443] = null
        this.m_achievements[ClassachievementData.ID444] = null
        this.m_achievements[ClassachievementData.ID445] = null
        this.m_achievements[ClassachievementData.ID446] = null
        this.m_achievements[ClassachievementData.ID447] = null
        this.m_achievements[ClassachievementData.ID448] = null
        this.m_achievements[ClassachievementData.ID449] = null
        this.m_achievements[ClassachievementData.ID450] = null
        this.m_achievements[ClassachievementData.ID451] = null
        this.m_achievements[ClassachievementData.ID452] = null
        this.m_achievements[ClassachievementData.ID453] = null
        this.m_achievements[ClassachievementData.ID454] = null
        this.m_achievements[ClassachievementData.ID455] = null
        this.m_achievements[ClassachievementData.ID456] = null
        this.m_achievements[ClassachievementData.ID457] = null
        this.m_achievements[ClassachievementData.ID458] = null
        this.m_achievements[ClassachievementData.ID459] = null
        this.m_achievements[ClassachievementData.ID460] = null
        this.m_achievements[ClassachievementData.ID461] = null
        this.m_achievements[ClassachievementData.ID462] = null
        this.m_achievements[ClassachievementData.ID463] = null
        this.m_achievements[ClassachievementData.ID464] = null
        this.m_achievements[ClassachievementData.ID465] = null
        this.m_achievements[ClassachievementData.ID466] = null
        this.m_achievements[ClassachievementData.ID467] = null
        this.m_achievements[ClassachievementData.ID468] = null
        this.m_achievements[ClassachievementData.ID469] = null
        this.m_achievements[ClassachievementData.ID470] = null
        this.m_achievements[ClassachievementData.ID471] = null
        this.m_achievements[ClassachievementData.ID472] = null
        this.m_achievements[ClassachievementData.ID473] = null
        this.m_achievements[ClassachievementData.ID474] = null
        this.m_achievements[ClassachievementData.ID475] = null
        this.m_achievements[ClassachievementData.ID476] = null
        this.m_achievements[ClassachievementData.ID477] = null
        this.m_achievements[ClassachievementData.ID478] = null
        this.m_achievements[ClassachievementData.ID479] = null
        this.m_achievements[ClassachievementData.ID480] = null
        this.m_achievements[ClassachievementData.ID481] = null
        this.m_achievements[ClassachievementData.ID482] = null
        this.m_achievements[ClassachievementData.ID483] = null
        this.m_achievements[ClassachievementData.ID484] = null
        this.m_achievements[ClassachievementData.ID485] = null
        this.m_achievements[ClassachievementData.ID486] = null
        this.m_achievements[ClassachievementData.ID487] = null
        this.m_achievements[ClassachievementData.ID488] = null
        this.m_achievements[ClassachievementData.ID489] = null
        this.m_achievements[ClassachievementData.ID490] = null
        this.m_achievements[ClassachievementData.ID491] = null
        this.m_achievements[ClassachievementData.ID492] = null
        this.m_achievements[ClassachievementData.ID493] = null
        this.m_achievements[ClassachievementData.ID494] = null
        this.m_achievements[ClassachievementData.ID495] = null
        this.m_achievements[ClassachievementData.ID496] = null
        this.m_achievements[ClassachievementData.ID497] = null
        this.m_achievements[ClassachievementData.ID498] = null
        this.m_achievements[ClassachievementData.ID499] = null
        this.m_achievements[ClassachievementData.ID500] = null
        this.m_achievements[ClassachievementData.ID501] = null
        this.m_achievements[ClassachievementData.ID502] = null
        this.m_achievements[ClassachievementData.ID503] = null
        this.m_achievements[ClassachievementData.ID504] = null
        this.m_achievements[ClassachievementData.ID505] = null
        this.m_achievements[ClassachievementData.ID506] = null
        this.m_achievements[ClassachievementData.ID507] = null
        this.m_achievements[ClassachievementData.ID508] = null
        this.m_achievements[ClassachievementData.ID509] = null
        this.m_achievements[ClassachievementData.ID510] = null
        this.m_achievements[ClassachievementData.ID511] = null
        this.m_achievements[ClassachievementData.ID536] = null
        this.m_achievements[ClassachievementData.ID537] = null
        this.m_achievements[ClassachievementData.ID538] = null
        this.m_achievements[ClassachievementData.ID539] = null
        this.m_achievements[ClassachievementData.ID581] = null
        this.m_achievements[ClassachievementData.ID585] = null
        this.m_achievements[ClassachievementData.ID586] = null
        this.m_achievements[ClassachievementData.ID587] = null
        this.m_achievements[ClassachievementData.ID588] = null
        this.m_achievements[ClassachievementData.ID589] = null
        this.m_achievements[ClassachievementData.ID590] = null
        this.m_achievements[ClassachievementData.ID591] = null
        this.m_achievements[ClassachievementData.ID624] = null
        this.m_achievements[ClassachievementData.ID625] = null
        this.m_achievements[ClassachievementData.ID626] = null
        this.m_achievements[ClassachievementData.ID627] = null
        this.m_achievements[ClassachievementData.ID628] = null
        this.m_achievements[ClassachievementData.ID630] = null
        this.m_achievements[ClassachievementData.ID631] = null
        this.m_achievements[ClassachievementData.ID632] = null
        this.m_achievements[ClassachievementData.ID633] = null
        this.m_achievements[ClassachievementData.ID634] = null
        this.m_achievements[ClassachievementData.ID662] = null
        this.m_achievements[ClassachievementData.ID672] = null
        this.m_achievements[ClassachievementData.ID679] = null
        this.m_achievements[ClassachievementData.ID680] = null
        this.m_achievements[ClassachievementData.ID684] = null
        this.m_achievements[ClassachievementData.ID685] = null
        this.m_achievements[ClassachievementData.ID686] = null
        this.m_achievements[ClassachievementData.ID687] = null
        this.m_achievements[ClassachievementData.ID688] = null
        this.m_achievements[ClassachievementData.ID689] = null
        this.m_achievements[ClassachievementData.ID690] = null
        this.m_achievements[ClassachievementData.ID691] = null
    }
    private static ID1 = 1
    private static ID2 = 2
    private static ID3 = 3
    private static ID4 = 4
    private static ID5 = 5
    private static ID6 = 6
    private static ID7 = 7
    private static ID8 = 8
    private static ID9 = 9
    private static ID10 = 10
    private static ID11 = 11
    private static ID12 = 12
    private static ID13 = 13
    private static ID14 = 14
    private static ID15 = 15
    private static ID16 = 16
    private static ID17 = 17
    private static ID18 = 18
    private static ID19 = 19
    private static ID20 = 20
    private static ID21 = 21
    private static ID22 = 22
    private static ID23 = 23
    private static ID24 = 24
    private static ID25 = 25
    private static ID26 = 26
    private static ID27 = 27
    private static ID28 = 28
    private static ID29 = 29
    private static ID30 = 30
    private static ID31 = 31
    private static ID32 = 32
    private static ID33 = 33
    private static ID34 = 34
    private static ID35 = 35
    private static ID36 = 36
    private static ID37 = 37
    private static ID38 = 38
    private static ID39 = 39
    private static ID40 = 40
    private static ID41 = 41
    private static ID42 = 42
    private static ID43 = 43
    private static ID44 = 44
    private static ID45 = 45
    private static ID46 = 46
    private static ID47 = 47
    private static ID48 = 48
    private static ID49 = 49
    private static ID50 = 50
    private static ID51 = 51
    private static ID52 = 52
    private static ID53 = 53
    private static ID54 = 54
    private static ID55 = 55
    private static ID56 = 56
    private static ID57 = 57
    private static ID58 = 58
    private static ID59 = 59
    private static ID60 = 60
    private static ID61 = 61
    private static ID62 = 62
    private static ID63 = 63
    private static ID64 = 64
    private static ID65 = 65
    private static ID66 = 66
    private static ID67 = 67
    private static ID68 = 68
    private static ID69 = 69
    private static ID70 = 70
    private static ID71 = 71
    private static ID72 = 72
    private static ID73 = 73
    private static ID74 = 74
    private static ID75 = 75
    private static ID76 = 76
    private static ID77 = 77
    private static ID78 = 78
    private static ID79 = 79
    private static ID80 = 80
    private static ID81 = 81
    private static ID82 = 82
    private static ID83 = 83
    private static ID84 = 84
    private static ID85 = 85
    private static ID86 = 86
    private static ID87 = 87
    private static ID88 = 88
    private static ID89 = 89
    private static ID90 = 90
    private static ID91 = 91
    private static ID92 = 92
    private static ID93 = 93
    private static ID94 = 94
    private static ID95 = 95
    private static ID96 = 96
    private static ID97 = 97
    private static ID98 = 98
    private static ID99 = 99
    private static ID100 = 100
    private static ID101 = 101
    private static ID102 = 102
    private static ID103 = 103
    private static ID104 = 104
    private static ID105 = 105
    private static ID106 = 106
    private static ID107 = 107
    private static ID108 = 108
    private static ID109 = 109
    private static ID110 = 110
    private static ID111 = 111
    private static ID112 = 112
    private static ID113 = 113
    private static ID114 = 114
    private static ID115 = 115
    private static ID116 = 116
    private static ID117 = 117
    private static ID118 = 118
    private static ID119 = 119
    private static ID120 = 120
    private static ID121 = 121
    private static ID122 = 122
    private static ID123 = 123
    private static ID124 = 124
    private static ID125 = 125
    private static ID126 = 126
    private static ID127 = 127
    private static ID128 = 128
    private static ID129 = 129
    private static ID130 = 130
    private static ID131 = 131
    private static ID132 = 132
    private static ID133 = 133
    private static ID134 = 134
    private static ID135 = 135
    private static ID136 = 136
    private static ID137 = 137
    private static ID138 = 138
    private static ID139 = 139
    private static ID140 = 140
    private static ID141 = 141
    private static ID142 = 142
    private static ID143 = 143
    private static ID144 = 144
    private static ID145 = 145
    private static ID146 = 146
    private static ID147 = 147
    private static ID148 = 148
    private static ID149 = 149
    private static ID150 = 150
    private static ID151 = 151
    private static ID152 = 152
    private static ID153 = 153
    private static ID154 = 154
    private static ID155 = 155
    private static ID156 = 156
    private static ID157 = 157
    private static ID158 = 158
    private static ID159 = 159
    private static ID160 = 160
    private static ID161 = 161
    private static ID162 = 162
    private static ID163 = 163
    private static ID164 = 164
    private static ID165 = 165
    private static ID166 = 166
    private static ID167 = 167
    private static ID168 = 168
    private static ID169 = 169
    private static ID170 = 170
    private static ID171 = 171
    private static ID172 = 172
    private static ID173 = 173
    private static ID174 = 174
    private static ID175 = 175
    private static ID176 = 176
    private static ID177 = 177
    private static ID178 = 178
    private static ID179 = 179
    private static ID180 = 180
    private static ID181 = 181
    private static ID182 = 182
    private static ID183 = 183
    private static ID184 = 184
    private static ID185 = 185
    private static ID186 = 186
    private static ID187 = 187
    private static ID188 = 188
    private static ID189 = 189
    private static ID190 = 190
    private static ID191 = 191
    private static ID192 = 192
    private static ID193 = 193
    private static ID194 = 194
    private static ID195 = 195
    private static ID196 = 196
    private static ID197 = 197
    private static ID198 = 198
    private static ID199 = 199
    private static ID200 = 200
    private static ID201 = 201
    private static ID202 = 202
    private static ID203 = 203
    private static ID204 = 204
    private static ID205 = 205
    private static ID206 = 206
    private static ID207 = 207
    private static ID208 = 208
    private static ID209 = 209
    private static ID210 = 210
    private static ID211 = 211
    private static ID212 = 212
    private static ID213 = 213
    private static ID214 = 214
    private static ID215 = 215
    private static ID216 = 216
    private static ID217 = 217
    private static ID218 = 218
    private static ID219 = 219
    private static ID220 = 220
    private static ID221 = 221
    private static ID222 = 222
    private static ID223 = 223
    private static ID224 = 224
    private static ID225 = 225
    private static ID226 = 226
    private static ID227 = 227
    private static ID228 = 228
    private static ID229 = 229
    private static ID230 = 230
    private static ID231 = 231
    private static ID232 = 232
    private static ID233 = 233
    private static ID234 = 234
    private static ID235 = 235
    private static ID236 = 236
    private static ID237 = 237
    private static ID238 = 238
    private static ID239 = 239
    private static ID240 = 240
    private static ID241 = 241
    private static ID242 = 242
    private static ID243 = 243
    private static ID244 = 244
    private static ID245 = 245
    private static ID246 = 246
    private static ID247 = 247
    private static ID248 = 248
    private static ID249 = 249
    private static ID250 = 250
    private static ID251 = 251
    private static ID252 = 252
    private static ID253 = 253
    private static ID254 = 254
    private static ID255 = 255
    private static ID256 = 256
    private static ID257 = 257
    private static ID258 = 258
    private static ID259 = 259
    private static ID260 = 260
    private static ID261 = 261
    private static ID262 = 262
    private static ID263 = 263
    private static ID264 = 264
    private static ID265 = 265
    private static ID266 = 266
    private static ID267 = 267
    private static ID268 = 268
    private static ID269 = 269
    private static ID270 = 270
    private static ID271 = 271
    private static ID272 = 272
    private static ID273 = 273
    private static ID274 = 274
    private static ID275 = 275
    private static ID276 = 276
    private static ID277 = 277
    private static ID278 = 278
    private static ID279 = 279
    private static ID280 = 280
    private static ID281 = 281
    private static ID282 = 282
    private static ID283 = 283
    private static ID284 = 284
    private static ID285 = 285
    private static ID286 = 286
    private static ID287 = 287
    private static ID288 = 288
    private static ID289 = 289
    private static ID290 = 290
    private static ID291 = 291
    private static ID292 = 292
    private static ID293 = 293
    private static ID294 = 294
    private static ID295 = 295
    private static ID296 = 296
    private static ID297 = 297
    private static ID298 = 298
    private static ID299 = 299
    private static ID300 = 300
    private static ID301 = 301
    private static ID302 = 302
    private static ID303 = 303
    private static ID304 = 304
    private static ID305 = 305
    private static ID306 = 306
    private static ID307 = 307
    private static ID308 = 308
    private static ID309 = 309
    private static ID310 = 310
    private static ID311 = 311
    private static ID312 = 312
    private static ID313 = 313
    private static ID314 = 314
    private static ID315 = 315
    private static ID316 = 316
    private static ID317 = 317
    private static ID318 = 318
    private static ID319 = 319
    private static ID320 = 320
    private static ID321 = 321
    private static ID322 = 322
    private static ID323 = 323
    private static ID324 = 324
    private static ID325 = 325
    private static ID326 = 326
    private static ID327 = 327
    private static ID328 = 328
    private static ID329 = 329
    private static ID330 = 330
    private static ID331 = 331
    private static ID332 = 332
    private static ID333 = 333
    private static ID334 = 334
    private static ID335 = 335
    private static ID336 = 336
    private static ID337 = 337
    private static ID338 = 338
    private static ID339 = 339
    private static ID340 = 340
    private static ID341 = 341
    private static ID342 = 342
    private static ID343 = 343
    private static ID344 = 344
    private static ID345 = 345
    private static ID346 = 346
    private static ID347 = 347
    private static ID348 = 348
    private static ID349 = 349
    private static ID350 = 350
    private static ID351 = 351
    private static ID352 = 352
    private static ID353 = 353
    private static ID354 = 354
    private static ID355 = 355
    private static ID356 = 356
    private static ID357 = 357
    private static ID358 = 358
    private static ID359 = 359
    private static ID360 = 360
    private static ID361 = 361
    private static ID362 = 362
    private static ID363 = 363
    private static ID364 = 364
    private static ID365 = 365
    private static ID366 = 366
    private static ID367 = 367
    private static ID368 = 368
    private static ID369 = 369
    private static ID370 = 370
    private static ID371 = 371
    private static ID372 = 372
    private static ID373 = 373
    private static ID374 = 374
    private static ID375 = 375
    private static ID376 = 376
    private static ID377 = 377
    private static ID378 = 378
    private static ID379 = 379
    private static ID380 = 380
    private static ID381 = 381
    private static ID382 = 382
    private static ID383 = 383
    private static ID384 = 384
    private static ID385 = 385
    private static ID386 = 386
    private static ID387 = 387
    private static ID388 = 388
    private static ID389 = 389
    private static ID390 = 390
    private static ID391 = 391
    private static ID392 = 392
    private static ID393 = 393
    private static ID394 = 394
    private static ID395 = 395
    private static ID396 = 396
    private static ID397 = 397
    private static ID398 = 398
    private static ID399 = 399
    private static ID400 = 400
    private static ID401 = 401
    private static ID402 = 402
    private static ID403 = 403
    private static ID404 = 404
    private static ID405 = 405
    private static ID406 = 406
    private static ID407 = 407
    private static ID408 = 408
    private static ID409 = 409
    private static ID410 = 410
    private static ID411 = 411
    private static ID412 = 412
    private static ID413 = 413
    private static ID414 = 414
    private static ID415 = 415
    private static ID416 = 416
    private static ID417 = 417
    private static ID418 = 418
    private static ID419 = 419
    private static ID420 = 420
    private static ID421 = 421
    private static ID422 = 422
    private static ID423 = 423
    private static ID424 = 424
    private static ID425 = 425
    private static ID426 = 426
    private static ID427 = 427
    private static ID428 = 428
    private static ID429 = 429
    private static ID430 = 430
    private static ID431 = 431
    private static ID432 = 432
    private static ID433 = 433
    private static ID434 = 434
    private static ID435 = 435
    private static ID436 = 436
    private static ID437 = 437
    private static ID438 = 438
    private static ID439 = 439
    private static ID440 = 440
    private static ID441 = 441
    private static ID442 = 442
    private static ID443 = 443
    private static ID444 = 444
    private static ID445 = 445
    private static ID446 = 446
    private static ID447 = 447
    private static ID448 = 448
    private static ID449 = 449
    private static ID450 = 450
    private static ID451 = 451
    private static ID452 = 452
    private static ID453 = 453
    private static ID454 = 454
    private static ID455 = 455
    private static ID456 = 456
    private static ID457 = 457
    private static ID458 = 458
    private static ID459 = 459
    private static ID460 = 460
    private static ID461 = 461
    private static ID462 = 462
    private static ID463 = 463
    private static ID464 = 464
    private static ID465 = 465
    private static ID466 = 466
    private static ID467 = 467
    private static ID468 = 468
    private static ID469 = 469
    private static ID470 = 470
    private static ID471 = 471
    private static ID472 = 472
    private static ID473 = 473
    private static ID474 = 474
    private static ID475 = 475
    private static ID476 = 476
    private static ID477 = 477
    private static ID478 = 478
    private static ID479 = 479
    private static ID480 = 480
    private static ID481 = 481
    private static ID482 = 482
    private static ID483 = 483
    private static ID484 = 484
    private static ID485 = 485
    private static ID486 = 486
    private static ID487 = 487
    private static ID488 = 488
    private static ID489 = 489
    private static ID490 = 490
    private static ID491 = 491
    private static ID492 = 492
    private static ID493 = 493
    private static ID494 = 494
    private static ID495 = 495
    private static ID496 = 496
    private static ID497 = 497
    private static ID498 = 498
    private static ID499 = 499
    private static ID500 = 500
    private static ID501 = 501
    private static ID502 = 502
    private static ID503 = 503
    private static ID504 = 504
    private static ID505 = 505
    private static ID506 = 506
    private static ID507 = 507
    private static ID508 = 508
    private static ID509 = 509
    private static ID510 = 510
    private static ID511 = 511
    private static ID536 = 536
    private static ID537 = 537
    private static ID538 = 538
    private static ID539 = 539
    private static ID581 = 581
    private static ID585 = 585
    private static ID586 = 586
    private static ID587 = 587
    private static ID588 = 588
    private static ID589 = 589
    private static ID590 = 590
    private static ID591 = 591
    private static ID624 = 624
    private static ID625 = 625
    private static ID626 = 626
    private static ID627 = 627
    private static ID628 = 628
    private static ID630 = 630
    private static ID631 = 631
    private static ID632 = 632
    private static ID633 = 633
    private static ID634 = 634
    private static ID662 = 662
    private static ID672 = 672
    private static ID679 = 679
    private static ID680 = 680
    private static ID684 = 684
    private static ID685 = 685
    private static ID686 = 686
    private static ID687 = 687
    private static ID688 = 688
    private static ID689 = 689
    private static ID690 = 690
    private static ID691 = 691
}