import ClassRaceData from "./ClassRaceHorseData";

export default class ClassAchievementData {
    private m_represent: ClassRaceData
    private m_achievements: {[ID:number]: ClassRaceData | null}
    constructor(represent: ClassRaceData) {
        this.m_represent = represent
        this.m_achievements = {}
        this.m_achievements[ClassAchievementData.ID1] = null
        this.m_achievements[ClassAchievementData.ID4] = null
        this.m_achievements[ClassAchievementData.ID5] = null
        this.m_achievements[ClassAchievementData.ID6] = null
        this.m_achievements[ClassAchievementData.ID8] = null
        this.m_achievements[ClassAchievementData.ID12] = null
        this.m_achievements[ClassAchievementData.ID13] = null
        this.m_achievements[ClassAchievementData.ID14] = null
        this.m_achievements[ClassAchievementData.ID15] = null
        this.m_achievements[ClassAchievementData.ID16] = null
        this.m_achievements[ClassAchievementData.ID20] = null
        this.m_achievements[ClassAchievementData.ID21] = null
        this.m_achievements[ClassAchievementData.ID22] = null
        this.m_achievements[ClassAchievementData.ID23] = null
        this.m_achievements[ClassAchievementData.ID24] = null
        this.m_achievements[ClassAchievementData.ID25] = null
        this.m_achievements[ClassAchievementData.ID28] = null
        this.m_achievements[ClassAchievementData.ID32] = null
        this.m_achievements[ClassAchievementData.ID40] = null
        this.m_achievements[ClassAchievementData.ID41] = null
        this.m_achievements[ClassAchievementData.ID42] = null
        this.m_achievements[ClassAchievementData.ID43] = null
        this.m_achievements[ClassAchievementData.ID44] = null
        this.m_achievements[ClassAchievementData.ID48] = null
        this.m_achievements[ClassAchievementData.ID49] = null
        this.m_achievements[ClassAchievementData.ID50] = null
        this.m_achievements[ClassAchievementData.ID51] = null
        this.m_achievements[ClassAchievementData.ID54] = null
        this.m_achievements[ClassAchievementData.ID55] = null
        this.m_achievements[ClassAchievementData.ID56] = null
        this.m_achievements[ClassAchievementData.ID58] = null
        this.m_achievements[ClassAchievementData.ID59] = null
        this.m_achievements[ClassAchievementData.ID61] = null
        this.m_achievements[ClassAchievementData.ID65] = null
        this.m_achievements[ClassAchievementData.ID66] = null
        this.m_achievements[ClassAchievementData.ID67] = null
        this.m_achievements[ClassAchievementData.ID68] = null
        this.m_achievements[ClassAchievementData.ID69] = null
        this.m_achievements[ClassAchievementData.ID70] = null
        this.m_achievements[ClassAchievementData.ID71] = null
        this.m_achievements[ClassAchievementData.ID72] = null
        this.m_achievements[ClassAchievementData.ID73] = null
        this.m_achievements[ClassAchievementData.ID74] = null
        this.m_achievements[ClassAchievementData.ID75] = null
        this.m_achievements[ClassAchievementData.ID77] = null
        this.m_achievements[ClassAchievementData.ID78] = null
        this.m_achievements[ClassAchievementData.ID79] = null
        this.m_achievements[ClassAchievementData.ID80] = null
        this.m_achievements[ClassAchievementData.ID81] = null
        this.m_achievements[ClassAchievementData.ID82] = null
        this.m_achievements[ClassAchievementData.ID83] = null
        this.m_achievements[ClassAchievementData.ID84] = null
        this.m_achievements[ClassAchievementData.ID85] = null
        this.m_achievements[ClassAchievementData.ID86] = null
        this.m_achievements[ClassAchievementData.ID87] = null
        this.m_achievements[ClassAchievementData.ID88] = null
        this.m_achievements[ClassAchievementData.ID89] = null
        this.m_achievements[ClassAchievementData.ID90] = null
        this.m_achievements[ClassAchievementData.ID91] = null
        this.m_achievements[ClassAchievementData.ID92] = null
        this.m_achievements[ClassAchievementData.ID93] = null
        this.m_achievements[ClassAchievementData.ID94] = null
        this.m_achievements[ClassAchievementData.ID95] = null
        this.m_achievements[ClassAchievementData.ID96] = null
        this.m_achievements[ClassAchievementData.ID97] = null
        this.m_achievements[ClassAchievementData.ID98] = null
        this.m_achievements[ClassAchievementData.ID99] = null
        this.m_achievements[ClassAchievementData.ID101] = null
        this.m_achievements[ClassAchievementData.ID102] = null
        this.m_achievements[ClassAchievementData.ID105] = null
        this.m_achievements[ClassAchievementData.ID106] = null
        this.m_achievements[ClassAchievementData.ID107] = null
        this.m_achievements[ClassAchievementData.ID108] = null
        this.m_achievements[ClassAchievementData.ID109] = null
        this.m_achievements[ClassAchievementData.ID110] = null
        this.m_achievements[ClassAchievementData.ID113] = null
        this.m_achievements[ClassAchievementData.ID114] = null
        this.m_achievements[ClassAchievementData.ID115] = null
        this.m_achievements[ClassAchievementData.ID116] = null
        this.m_achievements[ClassAchievementData.ID117] = null
        this.m_achievements[ClassAchievementData.ID118] = null
        this.m_achievements[ClassAchievementData.ID119] = null
        this.m_achievements[ClassAchievementData.ID120] = null
        this.m_achievements[ClassAchievementData.ID121] = null
        this.m_achievements[ClassAchievementData.ID122] = null
        this.m_achievements[ClassAchievementData.ID123] = null
        this.m_achievements[ClassAchievementData.ID125] = null
        this.m_achievements[ClassAchievementData.ID126] = null
        this.m_achievements[ClassAchievementData.ID127] = null
        this.m_achievements[ClassAchievementData.ID129] = null
        this.m_achievements[ClassAchievementData.ID130] = null
        this.m_achievements[ClassAchievementData.ID131] = null
        this.m_achievements[ClassAchievementData.ID132] = null
        this.m_achievements[ClassAchievementData.ID133] = null
        this.m_achievements[ClassAchievementData.ID134] = null
        this.m_achievements[ClassAchievementData.ID135] = null
        this.m_achievements[ClassAchievementData.ID136] = null
        this.m_achievements[ClassAchievementData.ID140] = null
        this.m_achievements[ClassAchievementData.ID141] = null
        this.m_achievements[ClassAchievementData.ID144] = null
        this.m_achievements[ClassAchievementData.ID145] = null
        this.m_achievements[ClassAchievementData.ID146] = null
        this.m_achievements[ClassAchievementData.ID148] = null
        this.m_achievements[ClassAchievementData.ID149] = null
        this.m_achievements[ClassAchievementData.ID150] = null
        this.m_achievements[ClassAchievementData.ID152] = null
        this.m_achievements[ClassAchievementData.ID153] = null
        this.m_achievements[ClassAchievementData.ID154] = null
        this.m_achievements[ClassAchievementData.ID155] = null
        this.m_achievements[ClassAchievementData.ID156] = null
        this.m_achievements[ClassAchievementData.ID157] = null
        this.m_achievements[ClassAchievementData.ID160] = null
        this.m_achievements[ClassAchievementData.ID161] = null
        this.m_achievements[ClassAchievementData.ID162] = null
        this.m_achievements[ClassAchievementData.ID163] = null
        this.m_achievements[ClassAchievementData.ID164] = null
        this.m_achievements[ClassAchievementData.ID167] = null
        this.m_achievements[ClassAchievementData.ID171] = null
        this.m_achievements[ClassAchievementData.ID172] = null
        this.m_achievements[ClassAchievementData.ID173] = null
        this.m_achievements[ClassAchievementData.ID175] = null
        this.m_achievements[ClassAchievementData.ID176] = null
        this.m_achievements[ClassAchievementData.ID177] = null
        this.m_achievements[ClassAchievementData.ID178] = null
        this.m_achievements[ClassAchievementData.ID179] = null
        this.m_achievements[ClassAchievementData.ID180] = null
        this.m_achievements[ClassAchievementData.ID181] = null
        this.m_achievements[ClassAchievementData.ID182] = null
        this.m_achievements[ClassAchievementData.ID183] = null
        this.m_achievements[ClassAchievementData.ID184] = null
        this.m_achievements[ClassAchievementData.ID185] = null
        this.m_achievements[ClassAchievementData.ID186] = null
        this.m_achievements[ClassAchievementData.ID187] = null
        this.m_achievements[ClassAchievementData.ID188] = null
        this.m_achievements[ClassAchievementData.ID191] = null
        this.m_achievements[ClassAchievementData.ID195] = null
        this.m_achievements[ClassAchievementData.ID196] = null
        this.m_achievements[ClassAchievementData.ID197] = null
        this.m_achievements[ClassAchievementData.ID199] = null
        this.m_achievements[ClassAchievementData.ID200] = null
        this.m_achievements[ClassAchievementData.ID201] = null
        this.m_achievements[ClassAchievementData.ID203] = null
        this.m_achievements[ClassAchievementData.ID204] = null
        this.m_achievements[ClassAchievementData.ID205] = null
        this.m_achievements[ClassAchievementData.ID206] = null
        this.m_achievements[ClassAchievementData.ID211] = null
        this.m_achievements[ClassAchievementData.ID212] = null
        this.m_achievements[ClassAchievementData.ID213] = null
        this.m_achievements[ClassAchievementData.ID214] = null
        this.m_achievements[ClassAchievementData.ID215] = null
        this.m_achievements[ClassAchievementData.ID216] = null
        this.m_achievements[ClassAchievementData.ID219] = null
        this.m_achievements[ClassAchievementData.ID220] = null
        this.m_achievements[ClassAchievementData.ID221] = null
        this.m_achievements[ClassAchievementData.ID222] = null
        this.m_achievements[ClassAchievementData.ID223] = null
        this.m_achievements[ClassAchievementData.ID224] = null
        this.m_achievements[ClassAchievementData.ID225] = null
        this.m_achievements[ClassAchievementData.ID227] = null
        this.m_achievements[ClassAchievementData.ID235] = null
        this.m_achievements[ClassAchievementData.ID239] = null
        this.m_achievements[ClassAchievementData.ID240] = null
        this.m_achievements[ClassAchievementData.ID241] = null
        this.m_achievements[ClassAchievementData.ID242] = null
        this.m_achievements[ClassAchievementData.ID243] = null
        this.m_achievements[ClassAchievementData.ID247] = null
        this.m_achievements[ClassAchievementData.ID251] = null
        this.m_achievements[ClassAchievementData.ID255] = null
        this.m_achievements[ClassAchievementData.ID256] = null
        this.m_achievements[ClassAchievementData.ID257] = null
        this.m_achievements[ClassAchievementData.ID258] = null
        this.m_achievements[ClassAchievementData.ID259] = null
        this.m_achievements[ClassAchievementData.ID260] = null
        this.m_achievements[ClassAchievementData.ID262] = null
        this.m_achievements[ClassAchievementData.ID266] = null
        this.m_achievements[ClassAchievementData.ID267] = null
        this.m_achievements[ClassAchievementData.ID268] = null
        this.m_achievements[ClassAchievementData.ID269] = null
        this.m_achievements[ClassAchievementData.ID270] = null
        this.m_achievements[ClassAchievementData.ID271] = null
        this.m_achievements[ClassAchievementData.ID272] = null
        this.m_achievements[ClassAchievementData.ID273] = null
        this.m_achievements[ClassAchievementData.ID274] = null
        this.m_achievements[ClassAchievementData.ID275] = null
        this.m_achievements[ClassAchievementData.ID276] = null
        this.m_achievements[ClassAchievementData.ID278] = null
        this.m_achievements[ClassAchievementData.ID279] = null
        this.m_achievements[ClassAchievementData.ID280] = null
        this.m_achievements[ClassAchievementData.ID281] = null
        this.m_achievements[ClassAchievementData.ID282] = null
        this.m_achievements[ClassAchievementData.ID283] = null
        this.m_achievements[ClassAchievementData.ID284] = null
        this.m_achievements[ClassAchievementData.ID285] = null
        this.m_achievements[ClassAchievementData.ID286] = null
        this.m_achievements[ClassAchievementData.ID287] = null
        this.m_achievements[ClassAchievementData.ID288] = null
        this.m_achievements[ClassAchievementData.ID290] = null
        this.m_achievements[ClassAchievementData.ID291] = null
        this.m_achievements[ClassAchievementData.ID292] = null
        this.m_achievements[ClassAchievementData.ID293] = null
        this.m_achievements[ClassAchievementData.ID294] = null
        this.m_achievements[ClassAchievementData.ID295] = null
        this.m_achievements[ClassAchievementData.ID298] = null
        this.m_achievements[ClassAchievementData.ID299] = null
        this.m_achievements[ClassAchievementData.ID300] = null
        this.m_achievements[ClassAchievementData.ID301] = null
        this.m_achievements[ClassAchievementData.ID302] = null
        this.m_achievements[ClassAchievementData.ID303] = null
        this.m_achievements[ClassAchievementData.ID304] = null
        this.m_achievements[ClassAchievementData.ID306] = null
        this.m_achievements[ClassAchievementData.ID307] = null
        this.m_achievements[ClassAchievementData.ID308] = null
        this.m_achievements[ClassAchievementData.ID309] = null
        this.m_achievements[ClassAchievementData.ID310] = null
        this.m_achievements[ClassAchievementData.ID311] = null
        this.m_achievements[ClassAchievementData.ID314] = null
        this.m_achievements[ClassAchievementData.ID315] = null
        this.m_achievements[ClassAchievementData.ID316] = null
        this.m_achievements[ClassAchievementData.ID317] = null
        this.m_achievements[ClassAchievementData.ID318] = null
        this.m_achievements[ClassAchievementData.ID319] = null
        this.m_achievements[ClassAchievementData.ID320] = null
        this.m_achievements[ClassAchievementData.ID321] = null
        this.m_achievements[ClassAchievementData.ID322] = null
        this.m_achievements[ClassAchievementData.ID326] = null
        this.m_achievements[ClassAchievementData.ID332] = null
        this.m_achievements[ClassAchievementData.ID333] = null
        this.m_achievements[ClassAchievementData.ID339] = null
        this.m_achievements[ClassAchievementData.ID340] = null
        this.m_achievements[ClassAchievementData.ID341] = null
        this.m_achievements[ClassAchievementData.ID343] = null
        this.m_achievements[ClassAchievementData.ID344] = null
        this.m_achievements[ClassAchievementData.ID347] = null
        this.m_achievements[ClassAchievementData.ID348] = null
        this.m_achievements[ClassAchievementData.ID349] = null
        this.m_achievements[ClassAchievementData.ID351] = null
        this.m_achievements[ClassAchievementData.ID352] = null
        this.m_achievements[ClassAchievementData.ID353] = null
        this.m_achievements[ClassAchievementData.ID355] = null
        this.m_achievements[ClassAchievementData.ID356] = null
        this.m_achievements[ClassAchievementData.ID357] = null
        this.m_achievements[ClassAchievementData.ID358] = null
        this.m_achievements[ClassAchievementData.ID359] = null
        this.m_achievements[ClassAchievementData.ID360] = null
        this.m_achievements[ClassAchievementData.ID361] = null
        this.m_achievements[ClassAchievementData.ID363] = null
        this.m_achievements[ClassAchievementData.ID364] = null
        this.m_achievements[ClassAchievementData.ID365] = null
        this.m_achievements[ClassAchievementData.ID367] = null
        this.m_achievements[ClassAchievementData.ID368] = null
        this.m_achievements[ClassAchievementData.ID369] = null
        this.m_achievements[ClassAchievementData.ID371] = null
        this.m_achievements[ClassAchievementData.ID372] = null
        this.m_achievements[ClassAchievementData.ID375] = null
        this.m_achievements[ClassAchievementData.ID376] = null
        this.m_achievements[ClassAchievementData.ID377] = null
        this.m_achievements[ClassAchievementData.ID378] = null
        this.m_achievements[ClassAchievementData.ID379] = null
        this.m_achievements[ClassAchievementData.ID380] = null
        this.m_achievements[ClassAchievementData.ID381] = null
        this.m_achievements[ClassAchievementData.ID382] = null
        this.m_achievements[ClassAchievementData.ID383] = null
        this.m_achievements[ClassAchievementData.ID384] = null
        this.m_achievements[ClassAchievementData.ID391] = null
        this.m_achievements[ClassAchievementData.ID392] = null
        this.m_achievements[ClassAchievementData.ID395] = null
        this.m_achievements[ClassAchievementData.ID402] = null
        this.m_achievements[ClassAchievementData.ID406] = null
        this.m_achievements[ClassAchievementData.ID407] = null
        this.m_achievements[ClassAchievementData.ID410] = null
        this.m_achievements[ClassAchievementData.ID417] = null
        this.m_achievements[ClassAchievementData.ID436] = null
        this.m_achievements[ClassAchievementData.ID440] = null
        this.m_achievements[ClassAchievementData.ID441] = null
        this.m_achievements[ClassAchievementData.ID448] = null
        this.m_achievements[ClassAchievementData.ID452] = null
        this.m_achievements[ClassAchievementData.ID453] = null
        this.m_achievements[ClassAchievementData.ID456] = null
        this.m_achievements[ClassAchievementData.ID472] = null
        this.m_achievements[ClassAchievementData.ID476] = null
        this.m_achievements[ClassAchievementData.ID477] = null
        this.m_achievements[ClassAchievementData.ID483] = null
        this.m_achievements[ClassAchievementData.ID488] = null
        this.m_achievements[ClassAchievementData.ID492] = null
        this.m_achievements[ClassAchievementData.ID495] = null
        this.m_achievements[ClassAchievementData.ID499] = null
        this.m_achievements[ClassAchievementData.ID508] = null
        this.m_achievements[ClassAchievementData.ID536] = null
        this.m_achievements[ClassAchievementData.ID585] = null
    }

    public updateAchievement(data: ClassRaceData) {
        if (!ClassAchievementData.IDlist.includes(data.ID)) {
            return false
        }
        this.m_achievements[data.ID] = data
    }
    public getIDAchievementData(ID: number) {
        if (this.m_achievements[ID] != undefined) {
            return this.m_achievements[ID]
        } else {
            return null
        }
    }
    public get represent() { return this.m_represent}
    public get achievements() { return this.m_achievements}

    
    private static ID1: number = 1
    private static ID4: number = 4
    private static ID5: number = 5
    private static ID6: number = 6
    private static ID8: number = 8
    private static ID12: number = 12
    private static ID13: number = 13
    private static ID14: number = 14
    private static ID15: number = 15
    private static ID16: number = 16
    private static ID20: number = 20
    private static ID21: number = 21
    private static ID22: number = 22
    private static ID23: number = 23
    private static ID24: number = 24
    private static ID25: number = 25
    private static ID28: number = 28
    private static ID32: number = 32
    private static ID40: number = 40
    private static ID41: number = 41
    private static ID42: number = 42
    private static ID43: number = 43
    private static ID44: number = 44
    private static ID48: number = 48
    private static ID49: number = 49
    private static ID50: number = 50
    private static ID51: number = 51
    private static ID54: number = 54
    private static ID55: number = 55
    private static ID56: number = 56
    private static ID58: number = 58
    private static ID59: number = 59
    private static ID61: number = 61
    private static ID65: number = 65
    private static ID66: number = 66
    private static ID67: number = 67
    private static ID68: number = 68
    private static ID69: number = 69
    private static ID70: number = 70
    private static ID71: number = 71
    private static ID72: number = 72
    private static ID73: number = 73
    private static ID74: number = 74
    private static ID75: number = 75
    private static ID77: number = 77
    private static ID78: number = 78
    private static ID79: number = 79
    private static ID80: number = 80
    private static ID81: number = 81
    private static ID82: number = 82
    private static ID83: number = 83
    private static ID84: number = 84
    private static ID85: number = 85
    private static ID86: number = 86
    private static ID87: number = 87
    private static ID88: number = 88
    private static ID89: number = 89
    private static ID90: number = 90
    private static ID91: number = 91
    private static ID92: number = 92
    private static ID93: number = 93
    private static ID94: number = 94
    private static ID95: number = 95
    private static ID96: number = 96
    private static ID97: number = 97
    private static ID98: number = 98
    private static ID99: number = 99
    private static ID101: number = 101
    private static ID102: number = 102
    private static ID105: number = 105
    private static ID106: number = 106
    private static ID107: number = 107
    private static ID108: number = 108
    private static ID109: number = 109
    private static ID110: number = 110
    private static ID113: number = 113
    private static ID114: number = 114
    private static ID115: number = 115
    private static ID116: number = 116
    private static ID117: number = 117
    private static ID118: number = 118
    private static ID119: number = 119
    private static ID120: number = 120
    private static ID121: number = 121
    private static ID122: number = 122
    private static ID123: number = 123
    private static ID125: number = 125
    private static ID126: number = 126
    private static ID127: number = 127
    private static ID129: number = 129
    private static ID130: number = 130
    private static ID131: number = 131
    private static ID132: number = 132
    private static ID133: number = 133
    private static ID134: number = 134
    private static ID135: number = 135
    private static ID136: number = 136
    private static ID140: number = 140
    private static ID141: number = 141
    private static ID144: number = 144
    private static ID145: number = 145
    private static ID146: number = 146
    private static ID148: number = 148
    private static ID149: number = 149
    private static ID150: number = 150
    private static ID152: number = 152
    private static ID153: number = 153
    private static ID154: number = 154
    private static ID155: number = 155
    private static ID156: number = 156
    private static ID157: number = 157
    private static ID160: number = 160
    private static ID161: number = 161
    private static ID162: number = 162
    private static ID163: number = 163
    private static ID164: number = 164
    private static ID167: number = 167
    private static ID171: number = 171
    private static ID172: number = 172
    private static ID173: number = 173
    private static ID175: number = 175
    private static ID176: number = 176
    private static ID177: number = 177
    private static ID178: number = 178
    private static ID179: number = 179
    private static ID180: number = 180
    private static ID181: number = 181
    private static ID182: number = 182
    private static ID183: number = 183
    private static ID184: number = 184
    private static ID185: number = 185
    private static ID186: number = 186
    private static ID187: number = 187
    private static ID188: number = 188
    private static ID191: number = 191
    private static ID195: number = 195
    private static ID196: number = 196
    private static ID197: number = 197
    private static ID199: number = 199
    private static ID200: number = 200
    private static ID201: number = 201
    private static ID203: number = 203
    private static ID204: number = 204
    private static ID205: number = 205
    private static ID206: number = 206
    private static ID211: number = 211
    private static ID212: number = 212
    private static ID213: number = 213
    private static ID214: number = 214
    private static ID215: number = 215
    private static ID216: number = 216
    private static ID219: number = 219
    private static ID220: number = 220
    private static ID221: number = 221
    private static ID222: number = 222
    private static ID223: number = 223
    private static ID224: number = 224
    private static ID225: number = 225
    private static ID227: number = 227
    private static ID235: number = 235
    private static ID239: number = 239
    private static ID240: number = 240
    private static ID241: number = 241
    private static ID242: number = 242
    private static ID243: number = 243
    private static ID247: number = 247
    private static ID251: number = 251
    private static ID255: number = 255
    private static ID256: number = 256
    private static ID257: number = 257
    private static ID258: number = 258
    private static ID259: number = 259
    private static ID260: number = 260
    private static ID262: number = 262
    private static ID266: number = 266
    private static ID267: number = 267
    private static ID268: number = 268
    private static ID269: number = 269
    private static ID270: number = 270
    private static ID271: number = 271
    private static ID272: number = 272
    private static ID273: number = 273
    private static ID274: number = 274
    private static ID275: number = 275
    private static ID276: number = 276
    private static ID278: number = 278
    private static ID279: number = 279
    private static ID280: number = 280
    private static ID281: number = 281
    private static ID282: number = 282
    private static ID283: number = 283
    private static ID284: number = 284
    private static ID285: number = 285
    private static ID286: number = 286
    private static ID287: number = 287
    private static ID288: number = 288
    private static ID290: number = 290
    private static ID291: number = 291
    private static ID292: number = 292
    private static ID293: number = 293
    private static ID294: number = 294
    private static ID295: number = 295
    private static ID298: number = 298
    private static ID299: number = 299
    private static ID300: number = 300
    private static ID301: number = 301
    private static ID302: number = 302
    private static ID303: number = 303
    private static ID304: number = 304
    private static ID306: number = 306
    private static ID307: number = 307
    private static ID308: number = 308
    private static ID309: number = 309
    private static ID310: number = 310
    private static ID311: number = 311
    private static ID314: number = 314
    private static ID315: number = 315
    private static ID316: number = 316
    private static ID317: number = 317
    private static ID318: number = 318
    private static ID319: number = 319
    private static ID320: number = 320
    private static ID321: number = 321
    private static ID322: number = 322
    private static ID326: number = 326
    private static ID332: number = 332
    private static ID333: number = 333
    private static ID339: number = 339
    private static ID340: number = 340
    private static ID341: number = 341
    private static ID343: number = 343
    private static ID344: number = 344
    private static ID347: number = 347
    private static ID348: number = 348
    private static ID349: number = 349
    private static ID351: number = 351
    private static ID352: number = 352
    private static ID353: number = 353
    private static ID355: number = 355
    private static ID356: number = 356
    private static ID357: number = 357
    private static ID358: number = 358
    private static ID359: number = 359
    private static ID360: number = 360
    private static ID361: number = 361
    private static ID363: number = 363
    private static ID364: number = 364
    private static ID365: number = 365
    private static ID367: number = 367
    private static ID368: number = 368
    private static ID369: number = 369
    private static ID371: number = 371
    private static ID372: number = 372
    private static ID375: number = 375
    private static ID376: number = 376
    private static ID377: number = 377
    private static ID378: number = 378
    private static ID379: number = 379
    private static ID380: number = 380
    private static ID381: number = 381
    private static ID382: number = 382
    private static ID383: number = 383
    private static ID384: number = 384
    private static ID391: number = 391
    private static ID392: number = 392
    private static ID395: number = 395
    private static ID402: number = 402
    private static ID406: number = 406
    private static ID407: number = 407
    private static ID410: number = 410
    private static ID417: number = 417
    private static ID436: number = 436
    private static ID440: number = 440
    private static ID441: number = 441
    private static ID448: number = 448
    private static ID452: number = 452
    private static ID453: number = 453
    private static ID456: number = 456
    private static ID472: number = 472
    private static ID476: number = 476
    private static ID477: number = 477
    private static ID483: number = 483
    private static ID488: number = 488
    private static ID492: number = 492
    private static ID495: number = 495
    private static ID499: number = 499
    private static ID508: number = 508
    private static ID536: number = 536
    private static ID585: number = 585
    private static IDlist = [ClassAchievementData.ID1, ClassAchievementData.ID4, ClassAchievementData.ID5, ClassAchievementData.ID6, ClassAchievementData.ID8, ClassAchievementData.ID12, ClassAchievementData.ID13, ClassAchievementData.ID14, ClassAchievementData.ID15, ClassAchievementData.ID16, ClassAchievementData.ID20, ClassAchievementData.ID21, ClassAchievementData.ID22, ClassAchievementData.ID23, ClassAchievementData.ID24, ClassAchievementData.ID25, ClassAchievementData.ID28, ClassAchievementData.ID32, ClassAchievementData.ID40, ClassAchievementData.ID41, ClassAchievementData.ID42, ClassAchievementData.ID43, ClassAchievementData.ID44, ClassAchievementData.ID48, ClassAchievementData.ID49, ClassAchievementData.ID50, ClassAchievementData.ID51, ClassAchievementData.ID54, ClassAchievementData.ID55, ClassAchievementData.ID56, ClassAchievementData.ID58, ClassAchievementData.ID59, ClassAchievementData.ID61, ClassAchievementData.ID65, ClassAchievementData.ID66, ClassAchievementData.ID67, ClassAchievementData.ID68, ClassAchievementData.ID69, ClassAchievementData.ID70, ClassAchievementData.ID71, ClassAchievementData.ID72, ClassAchievementData.ID73, ClassAchievementData.ID74, ClassAchievementData.ID75, ClassAchievementData.ID77, ClassAchievementData.ID78, ClassAchievementData.ID79, ClassAchievementData.ID80, ClassAchievementData.ID81, ClassAchievementData.ID82, ClassAchievementData.ID83, ClassAchievementData.ID84, ClassAchievementData.ID85, ClassAchievementData.ID86, ClassAchievementData.ID87, ClassAchievementData.ID88, ClassAchievementData.ID89, ClassAchievementData.ID90, ClassAchievementData.ID91, ClassAchievementData.ID92, ClassAchievementData.ID93, ClassAchievementData.ID94, ClassAchievementData.ID95, ClassAchievementData.ID96, ClassAchievementData.ID97, ClassAchievementData.ID98, ClassAchievementData.ID99, ClassAchievementData.ID101, ClassAchievementData.ID102, ClassAchievementData.ID105, ClassAchievementData.ID106, ClassAchievementData.ID107, ClassAchievementData.ID108, ClassAchievementData.ID109, ClassAchievementData.ID110, ClassAchievementData.ID113, ClassAchievementData.ID114, ClassAchievementData.ID115, ClassAchievementData.ID116, ClassAchievementData.ID117, ClassAchievementData.ID118, ClassAchievementData.ID119, ClassAchievementData.ID120, ClassAchievementData.ID121, ClassAchievementData.ID122, ClassAchievementData.ID123, ClassAchievementData.ID125, ClassAchievementData.ID126, ClassAchievementData.ID127, ClassAchievementData.ID129, ClassAchievementData.ID130, ClassAchievementData.ID131, ClassAchievementData.ID132, ClassAchievementData.ID133, ClassAchievementData.ID134, ClassAchievementData.ID135, ClassAchievementData.ID136, ClassAchievementData.ID140, ClassAchievementData.ID141, ClassAchievementData.ID144, ClassAchievementData.ID145, ClassAchievementData.ID146, ClassAchievementData.ID148, ClassAchievementData.ID149, ClassAchievementData.ID150, ClassAchievementData.ID152, ClassAchievementData.ID153, ClassAchievementData.ID154, ClassAchievementData.ID155, ClassAchievementData.ID156, ClassAchievementData.ID157, ClassAchievementData.ID160, ClassAchievementData.ID161, ClassAchievementData.ID162, ClassAchievementData.ID163, ClassAchievementData.ID164, ClassAchievementData.ID167, ClassAchievementData.ID171, ClassAchievementData.ID172, ClassAchievementData.ID173, ClassAchievementData.ID175, ClassAchievementData.ID176, ClassAchievementData.ID177, ClassAchievementData.ID178, ClassAchievementData.ID179, ClassAchievementData.ID180, ClassAchievementData.ID181, ClassAchievementData.ID182, ClassAchievementData.ID183, ClassAchievementData.ID184, ClassAchievementData.ID185, ClassAchievementData.ID186, ClassAchievementData.ID187, ClassAchievementData.ID188, ClassAchievementData.ID191, ClassAchievementData.ID195, ClassAchievementData.ID196, ClassAchievementData.ID197, ClassAchievementData.ID199, ClassAchievementData.ID200, ClassAchievementData.ID201, ClassAchievementData.ID203, ClassAchievementData.ID204, ClassAchievementData.ID205, ClassAchievementData.ID206, ClassAchievementData.ID211, ClassAchievementData.ID212, ClassAchievementData.ID213, ClassAchievementData.ID214, ClassAchievementData.ID215, ClassAchievementData.ID216, ClassAchievementData.ID219, ClassAchievementData.ID220, ClassAchievementData.ID221, ClassAchievementData.ID222, ClassAchievementData.ID223, ClassAchievementData.ID224, ClassAchievementData.ID225, ClassAchievementData.ID227, ClassAchievementData.ID235, ClassAchievementData.ID239, ClassAchievementData.ID240, ClassAchievementData.ID241, ClassAchievementData.ID242, ClassAchievementData.ID243, ClassAchievementData.ID247, ClassAchievementData.ID251, ClassAchievementData.ID255, ClassAchievementData.ID256, ClassAchievementData.ID257, ClassAchievementData.ID258, ClassAchievementData.ID259, ClassAchievementData.ID260, ClassAchievementData.ID262, ClassAchievementData.ID266, ClassAchievementData.ID267, ClassAchievementData.ID268, ClassAchievementData.ID269, ClassAchievementData.ID270, ClassAchievementData.ID271, ClassAchievementData.ID272, ClassAchievementData.ID273, ClassAchievementData.ID274, ClassAchievementData.ID275, ClassAchievementData.ID276, ClassAchievementData.ID278, ClassAchievementData.ID279, ClassAchievementData.ID280, ClassAchievementData.ID281, ClassAchievementData.ID282, ClassAchievementData.ID283, ClassAchievementData.ID284, ClassAchievementData.ID285, ClassAchievementData.ID286, ClassAchievementData.ID287, ClassAchievementData.ID288, ClassAchievementData.ID290, ClassAchievementData.ID291, ClassAchievementData.ID292, ClassAchievementData.ID293, ClassAchievementData.ID294, ClassAchievementData.ID295, ClassAchievementData.ID298, ClassAchievementData.ID299, ClassAchievementData.ID300, ClassAchievementData.ID301, ClassAchievementData.ID302, ClassAchievementData.ID303, ClassAchievementData.ID304, ClassAchievementData.ID306, ClassAchievementData.ID307, ClassAchievementData.ID308, ClassAchievementData.ID309, ClassAchievementData.ID310, ClassAchievementData.ID311, ClassAchievementData.ID314, ClassAchievementData.ID315, ClassAchievementData.ID316, ClassAchievementData.ID317, ClassAchievementData.ID318, ClassAchievementData.ID319, ClassAchievementData.ID320, ClassAchievementData.ID321, ClassAchievementData.ID322, ClassAchievementData.ID326, ClassAchievementData.ID332, ClassAchievementData.ID333, ClassAchievementData.ID339, ClassAchievementData.ID340, ClassAchievementData.ID341, ClassAchievementData.ID343, ClassAchievementData.ID344, ClassAchievementData.ID347, ClassAchievementData.ID348, ClassAchievementData.ID349, ClassAchievementData.ID351, ClassAchievementData.ID352, ClassAchievementData.ID353, ClassAchievementData.ID355, ClassAchievementData.ID356, ClassAchievementData.ID357, ClassAchievementData.ID358, ClassAchievementData.ID359, ClassAchievementData.ID360, ClassAchievementData.ID361, ClassAchievementData.ID363, ClassAchievementData.ID364, ClassAchievementData.ID365, ClassAchievementData.ID367, ClassAchievementData.ID368, ClassAchievementData.ID369, ClassAchievementData.ID371, ClassAchievementData.ID372, ClassAchievementData.ID375, ClassAchievementData.ID376, ClassAchievementData.ID377, ClassAchievementData.ID378, ClassAchievementData.ID379, ClassAchievementData.ID380, ClassAchievementData.ID381, ClassAchievementData.ID382, ClassAchievementData.ID383, ClassAchievementData.ID384, ClassAchievementData.ID391, ClassAchievementData.ID392, ClassAchievementData.ID395, ClassAchievementData.ID402, ClassAchievementData.ID406, ClassAchievementData.ID407, ClassAchievementData.ID410, ClassAchievementData.ID417, ClassAchievementData.ID436, ClassAchievementData.ID440, ClassAchievementData.ID441, ClassAchievementData.ID448, ClassAchievementData.ID452, ClassAchievementData.ID453, ClassAchievementData.ID456, ClassAchievementData.ID472, ClassAchievementData.ID476, ClassAchievementData.ID477, ClassAchievementData.ID483, ClassAchievementData.ID488, ClassAchievementData.ID492, ClassAchievementData.ID495, ClassAchievementData.ID499, ClassAchievementData.ID508, ClassAchievementData.ID536, ClassAchievementData.ID585]
}