export default class EntPaceData{
    public pace: number
    public RaceID: number
    public HorseNo: number
    public Venue: number
    public HoldMonth: number
    public Hold: number
    public Day: number
    public Range: number
    public Ground: number
    public GroundCondition: number
    public Weather: number
    public HorseAge: number
    public HorseGender: number
    public HorseWeight: number
    public Fluctuation: number
    public Weight: number
    public JockeyID: number
    public Pace_1: number
    public Passage1_1: number
    public Passage2_1: number
    public Passage3_1: number
    public Passage4_1: number
    public Pace_2: number
    public Passage1_2: number
    public Passage2_2: number
    public Passage3_2: number
    public Passage4_2: number
    public Pace_3: number
    public Passage1_3: number
    public Passage2_3: number
    public Passage3_3: number
    public Passage4_3: number
    public Pace_4: number
    public Passage1_4: number
    public Passage2_4: number
    public Passage3_4: number
    public Passage4_4: number
    public Pace_5: number
    public Passage1_5: number
    public Passage2_5: number
    public Passage3_5: number
    public Passage4_5: number
    constructor(){
        this.pace = 0
        this.RaceID = 0
        this.HorseNo = 0
        this.Venue = 0
        this.HoldMonth = 0
        this.Hold = 0
        this.Day = 0
        this.Range = 0
        this.Ground = 0
        this.GroundCondition = 0
        this.Weather = 0
        this.HorseAge = 0
        this.HorseGender = 0
        this.HorseWeight = 0
        this.Fluctuation = 0
        this.Weight = 0
        this.JockeyID = 0
        this.Pace_1 = 0
        this.Passage1_1 = 0
        this.Passage2_1 = 0
        this.Passage3_1 = 0
        this.Passage4_1 = 0
        this.Pace_2 = 0
        this.Passage1_2 = 0
        this.Passage2_2 = 0
        this.Passage3_2 = 0
        this.Passage4_2 = 0
        this.Pace_3 = 0
        this.Passage1_3 = 0
        this.Passage2_3 = 0
        this.Passage3_3 = 0
        this.Passage4_3 = 0
        this.Pace_4 = 0
        this.Passage1_4 = 0
        this.Passage2_4 = 0
        this.Passage3_4 = 0
        this.Passage4_4 = 0
        this.Pace_5 = 0
        this.Passage1_5 = 0
        this.Passage2_5 = 0
        this.Passage3_5 = 0
        this.Passage4_5 = 0
    }
}